import '../../domain/entities/reciter_entity.dart';
import '../../domain/entities/recitation_style_entity.dart';

class ReciterCatalog {
  static const List<RecitationStyleEntity> styles = [
    RecitationStyleEntity(id: 1, name: 'ترتیل', englishName: 'murattal'),
    RecitationStyleEntity(id: 2, name: 'مجود', englishName: 'mujawwad'),
    RecitationStyleEntity(id: 3, name: 'آموزشی (معلم)', englishName: 'moallim'),
    RecitationStyleEntity(id: 4, name: 'ترجمه صوتی', englishName: 'translation'),
  ];

  static const List<ReciterEntity> allReciters = [
    ReciterEntity(
      id: 30,
      identifier: 'abdulsamad_64kbps_quranexplorer_com',
      name: 'استاد عبدالباسط (ترتیل) (64kbps)',
      englishName: 'AbdulSamad',
      arabicName: 'عبدالباسط عبدالصمد',
      subfolder: 'AbdulSamad_64kbps_QuranExplorer.Com',
      bitrate: '64kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/9d/Abdul_Basit_Abdul_Samad_at_Centenary_Celebration_Of_Darul_Uloom_Deoband_1980.jpg',
    ),
    ReciterEntity(
      id: 31,
      identifier: 'abdul_basit_mujawwad_128kbps',
      name: 'استاد عبدالباسط (مجود)',
      englishName: 'Abdul Basit Mujawwad',
      arabicName: 'عبدالباسط عبدالصمد',
      subfolder: 'Abdul_Basit_Mujawwad_128kbps',
      bitrate: '128kbps',
      styleId: 2,
      styleName: 'مجود',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/9d/Abdul_Basit_Abdul_Samad_at_Centenary_Celebration_Of_Darul_Uloom_Deoband_1980.jpg',
    ),
    ReciterEntity(
      id: 32,
      identifier: 'abdul_basit_murattal_192kbps',
      name: 'استاد عبدالباسط (ترتیل) (192kbps)',
      englishName: 'Abdul Basit Murattal',
      arabicName: 'عبدالباسط عبدالصمد',
      subfolder: 'Abdul_Basit_Murattal_192kbps',
      bitrate: '192kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/9d/Abdul_Basit_Abdul_Samad_at_Centenary_Celebration_Of_Darul_Uloom_Deoband_1980.jpg',
    ),
    ReciterEntity(
      id: 33,
      identifier: 'abdul_basit_murattal_64kbps',
      name: 'استاد عبدالباسط (ترتیل) (64kbps)',
      englishName: 'Abdul Basit Murattal',
      arabicName: 'عبدالباسط عبدالصمد',
      subfolder: 'Abdul_Basit_Murattal_64kbps',
      bitrate: '64kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/9d/Abdul_Basit_Abdul_Samad_at_Centenary_Celebration_Of_Darul_Uloom_Deoband_1980.jpg',
    ),
    ReciterEntity(
      id: 34,
      identifier: 'abdullaah_3awwaad_al_juhaynee_128kbps',
      name: 'استاد عبدالله الجهنی',
      englishName: 'Abdullaah 3awwaad Al-Juhaynee',
      arabicName: 'عبدالله الجهني',
      subfolder: 'Abdullaah_3awwaad_Al-Juhaynee_128kbps',
      bitrate: '128kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/25/Abdullah_Al_Juhany_%28Cropped%29.png',
    ),
    ReciterEntity(
      id: 35,
      identifier: 'abdullah_basfar_192kbps',
      name: 'استاد عبدالله بصفر (192kbps)',
      englishName: 'Abdullah Basfar',
      arabicName: 'عبد الله بصفر',
      subfolder: 'Abdullah_Basfar_192kbps',
      bitrate: '192kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: null,
    ),
    ReciterEntity(
      id: 36,
      identifier: 'abdullah_basfar_32kbps',
      name: 'استاد عبدالله بصفر (32kbps)',
      englishName: 'Abdullah Basfar',
      arabicName: 'عبد الله بصفر',
      subfolder: 'Abdullah_Basfar_32kbps',
      bitrate: '32kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: null,
    ),
    ReciterEntity(
      id: 37,
      identifier: 'abdullah_basfar_64kbps',
      name: 'استاد عبدالله بصفر (64kbps)',
      englishName: 'Abdullah Basfar',
      arabicName: 'عبد الله بصفر',
      subfolder: 'Abdullah_Basfar_64kbps',
      bitrate: '64kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: null,
    ),
    ReciterEntity(
      id: 38,
      identifier: 'abdullah_matroud_128kbps',
      name: 'استاد عبدالله مطرود',
      englishName: 'Abdullah Matroud',
      arabicName: 'عبدالله مطرود',
      subfolder: 'Abdullah_Matroud_128kbps',
      bitrate: '128kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/41/Abdullah_Al_Matroud.jpg',
    ),
    ReciterEntity(
      id: 39,
      identifier: 'abdurrahmaan_as_sudais_192kbps',
      name: 'استاد عبدالرحمن السدیس (192kbps)',
      englishName: 'Abdurrahmaan As-Sudais',
      arabicName: 'عبدالرحمن السديس',
      subfolder: 'Abdurrahmaan_As-Sudais_192kbps',
      bitrate: '192kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/18/Abdul-Rahman_Al-Sudais_%28Cropped%2C_2011%29.jpg',
    ),
    ReciterEntity(
      id: 40,
      identifier: 'abdurrahmaan_as_sudais_64kbps',
      name: 'استاد عبدالرحمن السدیس (64kbps)',
      englishName: 'Abdurrahmaan As-Sudais',
      arabicName: 'عبدالرحمن السديس',
      subfolder: 'Abdurrahmaan_As-Sudais_64kbps',
      bitrate: '64kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/18/Abdul-Rahman_Al-Sudais_%28Cropped%2C_2011%29.jpg',
    ),
    ReciterEntity(
      id: 42,
      identifier: 'abu_bakr_ash_shaatree_128kbps',
      name: 'استاد ابو بکر الشاطری',
      englishName: 'Abu Bakr Ash-Shaatree',
      arabicName: 'أبو بكر الشاطري',
      subfolder: 'Abu_Bakr_Ash-Shaatree_128kbps',
      bitrate: '128kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: null,
    ),
    ReciterEntity(
      id: 43,
      identifier: 'abu_bakr_ash_shaatree_64kbps',
      name: 'استاد ابو بکر الشاطری (64kbps)',
      englishName: 'Abu Bakr Ash-Shaatree',
      arabicName: 'أبو بكر الشاطري',
      subfolder: 'Abu_Bakr_Ash-Shaatree_64kbps',
      bitrate: '64kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: null,
    ),
    ReciterEntity(
      id: 44,
      identifier: 'ahmed_neana_128kbps',
      name: 'استاد Ahmed Neana',
      englishName: 'Ahmed Neana',
      arabicName: 'Ahmed Neana',
      subfolder: 'Ahmed_Neana_128kbps',
      bitrate: '128kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/a9/DrAhmedNeinaa.jpg',
    ),
    ReciterEntity(
      id: 45,
      identifier: 'ahmed_ibn_ali_al_ajamy_128kbps_ketaballah_net',
      name: 'استاد احمد بن علی العجمی',
      englishName: 'Ahmed ibn Ali al-Ajamy',
      arabicName: 'أحمد بن علي العجمي',
      subfolder: 'Ahmed_ibn_Ali_al-Ajamy_128kbps_ketaballah.net',
      bitrate: '128kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e5/Ahmad_bin_Ali_Al-Ajmi.png',
    ),
    ReciterEntity(
      id: 46,
      identifier: 'ahmed_ibn_ali_al_ajamy_64kbps_quranexplorer_com',
      name: 'استاد احمد بن علی العجمی (64kbps)',
      englishName: 'Ahmed ibn Ali al-Ajamy',
      arabicName: 'أحمد بن علي العجمي',
      subfolder: 'Ahmed_ibn_Ali_al-Ajamy_64kbps_QuranExplorer.Com',
      bitrate: '64kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e5/Ahmad_bin_Ali_Al-Ajmi.png',
    ),
    ReciterEntity(
      id: 47,
      identifier: 'akram_alalaqimy_128kbps',
      name: 'استاد Akram AlAlaqimy',
      englishName: 'Akram AlAlaqimy',
      arabicName: 'Akram AlAlaqimy',
      subfolder: 'Akram_AlAlaqimy_128kbps',
      bitrate: '128kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: null,
    ),
    ReciterEntity(
      id: 48,
      identifier: 'alafasy_128kbps',
      name: 'استاد مشاری العفاسی',
      englishName: 'Alafasy',
      arabicName: 'مشاري العفاسي',
      subfolder: 'Alafasy_128kbps',
      bitrate: '128kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/24/%D0%9C%D0%B8%D1%88%D0%B0%D1%80%D0%B8_%D0%A0%D0%B0%D1%88%D0%B8%D0%B4.jpg',
    ),
    ReciterEntity(
      id: 49,
      identifier: 'alafasy_64kbps',
      name: 'استاد مشاری العفاسی (64kbps)',
      englishName: 'Alafasy',
      arabicName: 'مشاري العفاسي',
      subfolder: 'Alafasy_64kbps',
      bitrate: '64kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/24/%D0%9C%D0%B8%D1%88%D0%B0%D1%80%D0%B8_%D0%A0%D0%B0%D1%88%D0%B8%D0%B4.jpg',
    ),
    ReciterEntity(
      id: 50,
      identifier: 'ali_hajjaj_alsuesy_128kbps',
      name: 'استاد Ali Hajjaj AlSuesy',
      englishName: 'Ali Hajjaj AlSuesy',
      arabicName: 'Ali Hajjaj AlSuesy',
      subfolder: 'Ali_Hajjaj_AlSuesy_128kbps',
      bitrate: '128kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: null,
    ),
    ReciterEntity(
      id: 51,
      identifier: 'ali_jaber_64kbps',
      name: 'استاد Ali Jaber (64kbps)',
      englishName: 'Ali Jaber',
      arabicName: 'Ali Jaber',
      subfolder: 'Ali_Jaber_64kbps',
      bitrate: '64kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: null,
    ),
    ReciterEntity(
      id: 52,
      identifier: 'ayman_sowaid_64kbps',
      name: 'استاد Ayman Sowaid (64kbps)',
      englishName: 'Ayman Sowaid',
      arabicName: 'Ayman Sowaid',
      subfolder: 'Ayman_Sowaid_64kbps',
      bitrate: '64kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e2/Aymen_souaid.jpg',
    ),
    ReciterEntity(
      id: 54,
      identifier: 'fares_abbad_64kbps',
      name: 'استاد Fares Abbad (64kbps)',
      englishName: 'Fares Abbad',
      arabicName: 'Fares Abbad',
      subfolder: 'Fares_Abbad_64kbps',
      bitrate: '64kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: null,
    ),
    ReciterEntity(
      id: 55,
      identifier: 'ghamadi_40kbps',
      name: 'استاد سعد الغامدی (40kbps)',
      englishName: 'Ghamadi',
      arabicName: 'سعد الغامدي',
      subfolder: 'Ghamadi_40kbps',
      bitrate: '40kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/43/Saad_al_Ghamdi.jpg',
    ),
    ReciterEntity(
      id: 56,
      identifier: 'hani_rifai_192kbps',
      name: 'استاد هانی الرفاعی (192kbps)',
      englishName: 'Hani Rifai',
      arabicName: 'هاني الرفاعي',
      subfolder: 'Hani_Rifai_192kbps',
      bitrate: '192kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: null,
    ),
    ReciterEntity(
      id: 57,
      identifier: 'hani_rifai_64kbps',
      name: 'استاد هانی الرفاعی (64kbps)',
      englishName: 'Hani Rifai',
      arabicName: 'هاني الرفاعي',
      subfolder: 'Hani_Rifai_64kbps',
      bitrate: '64kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: null,
    ),
    ReciterEntity(
      id: 58,
      identifier: 'hudhaify_128kbps',
      name: 'استاد علی بن عبدالرحمن الحذیفی',
      englishName: 'Hudhaify',
      arabicName: 'علي بن عبدالرحمن الحذيفي',
      subfolder: 'Hudhaify_128kbps',
      bitrate: '128kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/d7/Huthaify.jpg',
    ),
    ReciterEntity(
      id: 59,
      identifier: 'hudhaify_32kbps',
      name: 'استاد علی بن عبدالرحمن الحذیفی (32kbps)',
      englishName: 'Hudhaify',
      arabicName: 'علي بن عبدالرحمن الحذيفي',
      subfolder: 'Hudhaify_32kbps',
      bitrate: '32kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/d7/Huthaify.jpg',
    ),
    ReciterEntity(
      id: 60,
      identifier: 'hudhaify_64kbps',
      name: 'استاد علی بن عبدالرحمن الحذیفی (64kbps)',
      englishName: 'Hudhaify',
      arabicName: 'علي بن عبدالرحمن الحذيفي',
      subfolder: 'Hudhaify_64kbps',
      bitrate: '64kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/d7/Huthaify.jpg',
    ),
    ReciterEntity(
      id: 61,
      identifier: 'husary_128kbps',
      name: 'استاد محمود خلیل الحصری',
      englishName: 'Husary',
      arabicName: 'محمود خليل الحصري',
      subfolder: 'Husary_128kbps',
      bitrate: '128kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/70/Hussary.jpg',
    ),
    ReciterEntity(
      id: 62,
      identifier: 'husary_128kbps_mujawwad',
      name: 'استاد محمود خلیل الحصری',
      englishName: 'Husary',
      arabicName: 'محمود خليل الحصري',
      subfolder: 'Husary_128kbps_Mujawwad',
      bitrate: '128kbps',
      styleId: 2,
      styleName: 'مجود',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/70/Hussary.jpg',
    ),
    ReciterEntity(
      id: 63,
      identifier: 'husary_64kbps',
      name: 'استاد محمود خلیل الحصری (64kbps)',
      englishName: 'Husary',
      arabicName: 'محمود خليل الحصري',
      subfolder: 'Husary_64kbps',
      bitrate: '64kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/70/Hussary.jpg',
    ),
    ReciterEntity(
      id: 64,
      identifier: 'husary_muallim_128kbps',
      name: 'استاد محمود خلیل الحصری (آموزشی)',
      englishName: 'Husary Muallim',
      arabicName: 'محمود خليل الحصري',
      subfolder: 'Husary_Muallim_128kbps',
      bitrate: '128kbps',
      styleId: 3,
      styleName: 'آموزشی (معلم)',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/70/Hussary.jpg',
    ),
    ReciterEntity(
      id: 65,
      identifier: 'husary_mujawwad_64kbps',
      name: 'استاد محمود خلیل الحصری (64kbps)',
      englishName: 'Husary Mujawwad',
      arabicName: 'محمود خليل الحصري',
      subfolder: 'Husary_Mujawwad_64kbps',
      bitrate: '64kbps',
      styleId: 2,
      styleName: 'مجود',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/70/Hussary.jpg',
    ),
    ReciterEntity(
      id: 66,
      identifier: 'ibrahim_akhdar_32kbps',
      name: 'استاد ابراهیم الاخضر (32kbps)',
      englishName: 'Ibrahim Akhdar',
      arabicName: 'إبراهيم الأخضر',
      subfolder: 'Ibrahim_Akhdar_32kbps',
      bitrate: '32kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: null,
    ),
    ReciterEntity(
      id: 67,
      identifier: 'ibrahim_akhdar_64kbps',
      name: 'استاد ابراهیم الاخضر (64kbps)',
      englishName: 'Ibrahim Akhdar',
      arabicName: 'إبراهيم الأخضر',
      subfolder: 'Ibrahim_Akhdar_64kbps',
      bitrate: '64kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: null,
    ),
    ReciterEntity(
      id: 68,
      identifier: 'karim_mansoori_40kbps',
      name: 'استاد Karim Mansoori (40kbps)',
      englishName: 'Karim Mansoori',
      arabicName: 'Karim Mansoori',
      subfolder: 'Karim_Mansoori_40kbps',
      bitrate: '40kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: null,
    ),
    ReciterEntity(
      id: 69,
      identifier: 'khaalid_abdullaah_al_qahtaanee_192kbps',
      name: 'استاد Khaalid Abdullaah al-Qahtaanee (192kbps)',
      englishName: 'Khaalid Abdullaah al-Qahtaanee',
      arabicName: 'Khaalid Abdullaah al-Qahtaanee',
      subfolder: 'Khaalid_Abdullaah_al-Qahtaanee_192kbps',
      bitrate: '192kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: null,
    ),
    ReciterEntity(
      id: 70,
      identifier: 'maheralmuaiqly128kbps',
      name: 'استاد ماهر المعیقلی',
      englishName: 'MaherAlMuaiqly128kbps',
      arabicName: 'ماهر المعيقلي',
      subfolder: 'MaherAlMuaiqly128kbps',
      bitrate: '128kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/90/Maher_Al_Mueaqly.png',
    ),
    ReciterEntity(
      id: 71,
      identifier: 'maher_almuaiqly_64kbps',
      name: 'استاد ماهر المعیقلی (64kbps)',
      englishName: 'Maher AlMuaiqly',
      arabicName: 'ماهر المعيقلي',
      subfolder: 'Maher_AlMuaiqly_64kbps',
      bitrate: '64kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/90/Maher_Al_Mueaqly.png',
    ),
    ReciterEntity(
      id: 72,
      identifier: 'menshawi_16kbps',
      name: 'استاد Menshawi (16kbps)',
      englishName: 'Menshawi',
      arabicName: 'Menshawi',
      subfolder: 'Menshawi_16kbps',
      bitrate: '16kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/ee/Elminshwey.jpg',
    ),
    ReciterEntity(
      id: 73,
      identifier: 'menshawi_32kbps',
      name: 'استاد Menshawi (32kbps)',
      englishName: 'Menshawi',
      arabicName: 'Menshawi',
      subfolder: 'Menshawi_32kbps',
      bitrate: '32kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/ee/Elminshwey.jpg',
    ),
    ReciterEntity(
      id: 74,
      identifier: 'minshawy_mujawwad_192kbps',
      name: 'استاد محمد صدیق منشاوی (مجود) (192kbps)',
      englishName: 'Minshawy Mujawwad',
      arabicName: 'محمد صديق المنشاوي',
      subfolder: 'Minshawy_Mujawwad_192kbps',
      bitrate: '192kbps',
      styleId: 2,
      styleName: 'مجود',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/ee/Elminshwey.jpg',
    ),
    ReciterEntity(
      id: 75,
      identifier: 'minshawy_mujawwad_64kbps',
      name: 'استاد محمد صدیق منشاوی (مجود) (64kbps)',
      englishName: 'Minshawy Mujawwad',
      arabicName: 'محمد صديق المنشاوي',
      subfolder: 'Minshawy_Mujawwad_64kbps',
      bitrate: '64kbps',
      styleId: 2,
      styleName: 'مجود',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/ee/Elminshwey.jpg',
    ),
    ReciterEntity(
      id: 76,
      identifier: 'minshawy_murattal_128kbps',
      name: 'استاد محمد صدیق منشاوی (ترتیل)',
      englishName: 'Minshawy Murattal',
      arabicName: 'محمد صديق المنشاوي',
      subfolder: 'Minshawy_Murattal_128kbps',
      bitrate: '128kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/ee/Elminshwey.jpg',
    ),
    ReciterEntity(
      id: 77,
      identifier: 'minshawy_teacher_128kbps',
      name: 'استاد Minshawy Teacher',
      englishName: 'Minshawy Teacher',
      arabicName: 'Minshawy Teacher',
      subfolder: 'Minshawy_Teacher_128kbps',
      bitrate: '128kbps',
      styleId: 3,
      styleName: 'آموزشی (معلم)',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/ee/Elminshwey.jpg',
    ),
    ReciterEntity(
      id: 78,
      identifier: 'mohammad_al_tablaway_128kbps',
      name: 'استاد محمد الطبلاوی',
      englishName: 'Mohammad al Tablaway',
      arabicName: 'محمد الطبلاوي',
      subfolder: 'Mohammad_al_Tablaway_128kbps',
      bitrate: '128kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: null,
    ),
    ReciterEntity(
      id: 79,
      identifier: 'mohammad_al_tablaway_64kbps',
      name: 'استاد محمد الطبلاوی (64kbps)',
      englishName: 'Mohammad al Tablaway',
      arabicName: 'محمد الطبلاوي',
      subfolder: 'Mohammad_al_Tablaway_64kbps',
      bitrate: '64kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: null,
    ),
    ReciterEntity(
      id: 80,
      identifier: 'muhammad_abdulkareem_128kbps',
      name: 'استاد Muhammad AbdulKareem',
      englishName: 'Muhammad AbdulKareem',
      arabicName: 'Muhammad AbdulKareem',
      subfolder: 'Muhammad_AbdulKareem_128kbps',
      bitrate: '128kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: null,
    ),
    ReciterEntity(
      id: 81,
      identifier: 'muhammad_ayyoub_128kbps',
      name: 'استاد محمد ایوب',
      englishName: 'Muhammad Ayyoub',
      arabicName: 'محمد أيوب',
      subfolder: 'Muhammad_Ayyoub_128kbps',
      bitrate: '128kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: null,
    ),
    ReciterEntity(
      id: 82,
      identifier: 'muhammad_ayyoub_32kbps',
      name: 'استاد محمد ایوب (32kbps)',
      englishName: 'Muhammad Ayyoub',
      arabicName: 'محمد أيوب',
      subfolder: 'Muhammad_Ayyoub_32kbps',
      bitrate: '32kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: null,
    ),
    ReciterEntity(
      id: 83,
      identifier: 'muhammad_ayyoub_64kbps',
      name: 'استاد محمد ایوب (64kbps)',
      englishName: 'Muhammad Ayyoub',
      arabicName: 'محمد أيوب',
      subfolder: 'Muhammad_Ayyoub_64kbps',
      bitrate: '64kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: null,
    ),
    ReciterEntity(
      id: 84,
      identifier: 'muhammad_jibreel_128kbps',
      name: 'استاد محمد جبریل',
      englishName: 'Muhammad Jibreel',
      arabicName: 'محمد جبريل',
      subfolder: 'Muhammad_Jibreel_128kbps',
      bitrate: '128kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/3/32/Qari_Muhammad_Jebril%2C_Ramadan_2019.png',
    ),
    ReciterEntity(
      id: 85,
      identifier: 'muhammad_jibreel_64kbps',
      name: 'استاد محمد جبریل (64kbps)',
      englishName: 'Muhammad Jibreel',
      arabicName: 'محمد جبريل',
      subfolder: 'Muhammad_Jibreel_64kbps',
      bitrate: '64kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/3/32/Qari_Muhammad_Jebril%2C_Ramadan_2019.png',
    ),
    ReciterEntity(
      id: 86,
      identifier: 'muhsin_al_qasim_192kbps',
      name: 'استاد Muhsin Al Qasim (192kbps)',
      englishName: 'Muhsin Al Qasim',
      arabicName: 'Muhsin Al Qasim',
      subfolder: 'Muhsin_Al_Qasim_192kbps',
      bitrate: '192kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: null,
    ),
    ReciterEntity(
      id: 88,
      identifier: 'mustafa_ismail_48kbps',
      name: 'استاد Mustafa Ismail (48kbps)',
      englishName: 'Mustafa Ismail',
      arabicName: 'Mustafa Ismail',
      subfolder: 'Mustafa_Ismail_48kbps',
      bitrate: '48kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/a8/Mustafa_Ismail_%281%29.jpg',
    ),
    ReciterEntity(
      id: 89,
      identifier: 'nabil_rifa3i_48kbps',
      name: 'استاد Nabil Rifa3i (48kbps)',
      englishName: 'Nabil Rifa3i',
      arabicName: 'Nabil Rifa3i',
      subfolder: 'Nabil_Rifa3i_48kbps',
      bitrate: '48kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: null,
    ),
    ReciterEntity(
      id: 90,
      identifier: 'nasser_alqatami_128kbps',
      name: 'استاد Nasser Alqatami',
      englishName: 'Nasser Alqatami',
      arabicName: 'Nasser Alqatami',
      subfolder: 'Nasser_Alqatami_128kbps',
      bitrate: '128kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/c/ca/%D8%B5%D9%88%D8%B1%D8%A9_%D8%B4%D8%AE%D8%B5%D9%8A%D8%A9_%D8%A7%D9%84%D8%B4%D9%8A%D8%AE_%D9%86%D8%A7%D8%B5%D8%B1_%D8%A7%D9%84%D9%82%D8%B7%D8%A7%D9%85%D9%8A.jpg',
    ),
    ReciterEntity(
      id: 91,
      identifier: 'parhizgar_48kbps',
      name: 'استاد شهریار پرهیزگار (48kbps)',
      englishName: 'Parhizgar',
      arabicName: 'شهریار پرهیزگار',
      subfolder: 'Parhizgar_48kbps',
      bitrate: '48kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/a3/%D8%B4%D9%87%D8%B1%DB%8C%D8%A7%D8%B1_%D9%BE%D8%B1%D9%87%DB%8C%D8%B2%DA%A9%D8%A7%D8%B1_04_%281%29.jpg',
    ),
    ReciterEntity(
      id: 94,
      identifier: 'sahl_yassin_128kbps',
      name: 'استاد Sahl Yassin',
      englishName: 'Sahl Yassin',
      arabicName: 'Sahl Yassin',
      subfolder: 'Sahl_Yassin_128kbps',
      bitrate: '128kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: null,
    ),
    ReciterEntity(
      id: 95,
      identifier: 'salaah_abdulrahman_bukhatir_128kbps',
      name: 'استاد صلاح بوخاطر',
      englishName: 'Salaah AbdulRahman Bukhatir',
      arabicName: 'صلاح بوخاطر',
      subfolder: 'Salaah_AbdulRahman_Bukhatir_128kbps',
      bitrate: '128kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: null,
    ),
    ReciterEntity(
      id: 96,
      identifier: 'salah_al_budair_128kbps',
      name: 'استاد Salah Al Budair',
      englishName: 'Salah Al Budair',
      arabicName: 'Salah Al Budair',
      subfolder: 'Salah_Al_Budair_128kbps',
      bitrate: '128kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/df/Salah_Ibn_Mohammed_Al_Budair.jpg',
    ),
    ReciterEntity(
      id: 97,
      identifier: 'saood_bin_ibraaheem_ash_shuraym_128kbps',
      name: 'استاد سعود الشریم',
      englishName: 'Saood bin Ibraaheem Ash-Shuraym',
      arabicName: 'سعود الشريم',
      subfolder: 'Saood%20bin%20Ibraaheem%20Ash-Shuraym_128kbps',
      bitrate: '128kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/5/5d/Saud_Shuraim_doing_the_Khutbah.png',
    ),
    ReciterEntity(
      id: 98,
      identifier: 'saood_ash_shuraym_128kbps',
      name: 'استاد سعود الشریم',
      englishName: 'Saood ash-Shuraym',
      arabicName: 'سعود الشريم',
      subfolder: 'Saood_ash-Shuraym_128kbps',
      bitrate: '128kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/5/5d/Saud_Shuraim_doing_the_Khutbah.png',
    ),
    ReciterEntity(
      id: 99,
      identifier: 'saood_ash_shuraym_64kbps',
      name: 'استاد سعود الشریم (64kbps)',
      englishName: 'Saood ash-Shuraym',
      arabicName: 'سعود الشريم',
      subfolder: 'Saood_ash-Shuraym_64kbps',
      bitrate: '64kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/5/5d/Saud_Shuraim_doing_the_Khutbah.png',
    ),
    ReciterEntity(
      id: 101,
      identifier: 'yaser_salamah_128kbps',
      name: 'استاد Yaser Salamah',
      englishName: 'Yaser Salamah',
      arabicName: 'Yaser Salamah',
      subfolder: 'Yaser_Salamah_128kbps',
      bitrate: '128kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: null,
    ),
    ReciterEntity(
      id: 102,
      identifier: 'yasser_ad_dussary_128kbps',
      name: 'استاد Yasser Ad-Dussary',
      englishName: 'Yasser Ad-Dussary',
      arabicName: 'Yasser Ad-Dussary',
      subfolder: 'Yasser_Ad-Dussary_128kbps',
      bitrate: '128kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Yasser_Al-Dosari_%28cropped%29.jpg',
    ),
    ReciterEntity(
      id: 103,
      identifier: 'ahmed_ibn_ali_al_ajamy_128kbps',
      name: 'استاد احمد بن علی العجمی',
      englishName: 'ahmed ibn ali al ajamy',
      arabicName: 'أحمد بن علي العجمي',
      subfolder: 'ahmed_ibn_ali_al_ajamy_128kbps',
      bitrate: '128kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e5/Ahmad_bin_Ali_Al-Ajmi.png',
    ),
    ReciterEntity(
      id: 104,
      identifier: 'aziz_alili_128kbps',
      name: 'استاد aziz alili',
      englishName: 'aziz alili',
      arabicName: 'aziz alili',
      subfolder: 'aziz_alili_128kbps',
      bitrate: '128kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: null,
    ),
    ReciterEntity(
      id: 106,
      identifier: 'khalefa_al_tunaiji_64kbps',
      name: 'استاد khalefa al tunaiji (64kbps)',
      englishName: 'khalefa al tunaiji',
      arabicName: 'khalefa al tunaiji',
      subfolder: 'khalefa_al_tunaiji_64kbps',
      bitrate: '64kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: null,
    ),
    ReciterEntity(
      id: 107,
      identifier: 'mahmoud_ali_al_banna_32kbps',
      name: 'استاد محمود علی البنا (32kbps)',
      englishName: 'mahmoud ali al banna',
      arabicName: 'محمود علي البنا',
      subfolder: 'mahmoud_ali_al_banna_32kbps',
      bitrate: '32kbps',
      styleId: 1,
      styleName: 'ترتیل',
      imageUrl: null,
    ),
  ];
}
